### ISSUE TITLE
error when i start a job

### ISSUE THREAD

**Issue by archonveins** [DaGooseYT/FrameGUI#21]
log contents:
`#================================================#
FrameGUI process logs for job 21474711
Video encoding arguments: C:\Users\archonveins\AppData\Local\Programs\FrameGUI\vs\vspipe.exe -c y4m C:\Users\archonveins\AppData\Local\FrameGUI\job-21474711\21474711.vpy - | C:\Users\archonveins\AppData\Local\Programs\FrameGUI\ffmpeg\ffmpeg.exe -y -noautorotate -i - -c:v libx264 -crf 17 -metadata:g encoding_tool="FrameGUI v2.2.0" C:\Users\archonveins\AppData\Local\Temp\21474711.mkv
Audio encoding arguments: C:\Users\archonveins\AppData\Local\Programs\FrameGUI\ffmpeg\ffmpeg.exe -y -i C:\Users\archonveins\AppData\Local\Temp\21474711.mkv -i C:\Users\archonveins\Pictures\1b9a2cf71b4ffd35704736c83d9b288e.mp4 -map 0:v -c:v copy -map 1:a -c:a copy -map 1:s? -c:s mov_text -metadata:g encoding_tool="FrameGUI v2.2.0" C:\Users\archonveins\Documents\1b9a2cf71b4ffd35704736c83d9b288e.mp4
#================================================#

ffmpeg version n5.1-1-g6d83c5f876-20220727 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220727
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100

[0 Intel(R) HD Graphics 620]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) HD Graphics 620]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) HD Graphics 620]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) HD Graphics 620]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 NVIDIA GeForce 940MX]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[1 NVIDIA GeForce 940MX]  bugsbn1=0  bugbilz=83  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce 940MX]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[1 NVIDIA GeForce 940MX]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
Script evaluation failed:
Python exception: RIFE: gpu_thread must be between 1 and 1 (inclusive)

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2759, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2760, in vapoursynth._vpy_evaluate
  File "C:\Users\archonveins\AppData\Local\FrameGUI\job-21474711\21474711.vpy", line 15, in <module>
    clip = core.rife.RIFE(clip, model=0, fps_num=60, fps_den=1, gpu_id=0, gpu_thread=2, tta=False, uhd=False, sc=True)
  File "src\cython\vapoursynth.pyx", line 2507, in vapoursynth.Function.__call__
vapoursynth.Error: RIFE: gpu_thread must be between 1 and 1 (inclusive)

pipe:: Invalid data found when processing input

#================================================#
End of logs
#================================================#
`
this happens on my old pc only

**Comment by HubbyGitter** [comment]
I think I have the same issue.
But first I'd like to say "thank you" for FrameGUI. I played a bit with it and got some nice results.
Today I decided to use my "CPU"'s GPU 0 graphics for my desktop and reserve my PCIe graphics card for computations. And now I can't use FrameGUI anymore.

The log text is the same as above until the GPUs are listed:
```
[0 AMD Radeon(TM) Graphics]  queueC=1[4]  queueG=0[2]  queueT=2[1]
[0 AMD Radeon(TM) Graphics]  buglssc=0  bugsbn1=0  buglbia=0  bugihfa=0
[0 AMD Radeon(TM) Graphics]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
[1 NVIDIA GeForce RTX 5060 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce RTX 5060 Ti]  buglssc=0  bugsbn1=0  buglbia=0  bugihfa=0
[1 NVIDIA GeForce RTX 5060 Ti]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
vkAllocateMemory failed -2
vkAllocateMemory failed -2
pipe:: Invalid data found when processing input
```

This is Windows 11 so I tried to assign GPU 1 to FrameGUI. This leads to FrameGUI showing "[GPU 0: NVIDIA GeForce RTX 5060 Ti]" in the window title bar (but the failure log still shows the Radeon as GPU 0). The problem remains.

I downloaded EncodeGUI and there I'm able to select the GPU it seems. However:

- Can I achieve the same with EncodeGUI?
- If yes, what are the EncodeGUI options that FrameGUI silently uses?

I'm asking because it appeared to me that by RTX was by far not fully deployed by EncodeGUI with one function although it used to be when using FrameGUI.

I might be able to look into the code nd contribute, but would be nice to get some tips upfront if possible.

**Comment by Bobiaj14** [comment]
#================================================#
FrameGUI process logs for job 0845479
Video encoding arguments: F:\FrameGUI\vs\vspipe.exe -c y4m C:\Users\Computer\AppData\Local\FrameGUI\job-0845479\0845479.vpy - | F:\FrameGUI\ffmpeg\ffmpeg.exe -y -noautorotate -i - -c:v libx264 -crf 17 -metadata:g encoding_tool="FrameGUI v2.2.0" C:\Users\Computer\AppData\Local\Temp\0845479.mkv
Audio encoding arguments: F:\FrameGUI\ffmpeg\ffmpeg.exe -y -i C:\Users\Computer\AppData\Local\Temp\0845479.mkv -i F:\Telenovela\El Diario De Daniela\51-75\52.mkv -map 0:v -c:v copy -map 1:a -c:a copy -map 1:s? -c:s mov_text -metadata:g encoding_tool="FrameGUI v2.2.0" C:\Users\Computer\Desktop\52.mp4
#================================================#

ffmpeg version n5.1-1-g6d83c5f876-20220727 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (crosstool-NG 1.25.0.55_3defb7b)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220727
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100

pipe:: Invalid data found when processing input

#================================================#
End of logs
#================================================#


so is there any way to fix?

i tried the old frame gui and the app said cannot detect fps from input video hmm...
is because some missing dll or something?
